language: php

php:
  - 5.3
  - 5.4
  - 5.5
  
services: 
  - mysql
 
branches:
  only:
    - master
    
notifications:
  email: false

before_script:
  - mysql -e 'create database neobazaar_fixture;'
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --prefer-dist --dev
  
script:
  - mkdir -p build/logs
  - ./vendor/bin/phpunit --coverage-clover ./../build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v